### ISSUE TITLE
HTML Resume Part 2 -- Gist

### ISSUE THREAD

**Issue by mpopv** [ga-dc/html_resume#70]
http://htmlpreview.github.io/?https://gist.githubusercontent.com/mpopv/20957fa8e56d0d549e28/raw/a8567e98c1c4341d5ba62000de69d93a8a9b0d9c/index.html

**Comment by mattscilipoti** [comment]
:+1: Looks good.

Thanks for sharing htmlpreview.  I wasn't aware of that tool.
I recommend not using the h4 for the company name.  That information is supporting the h3, not creating another section.  This feels like a case of using the h4 for it's formatting, rather than grouping.

In the future, please include comfort/completion feedback, per [](https://github.com/ga-dc/wdi7/blob/master/homework/submission-process.md)
