### ISSUE TITLE
Kory J. Campbell Week 1 Day 2 Homework

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-dc/html_resume#92]
http://htmlpreview.github.io/?https://gist.githubusercontent.com/KoryJCampbell/ab04daf32ed24472eaf5/raw/248bdb82bdc39db8da38901bcecfb5cac1411bee/Kory%2520J.%2520Campbell%2520Day%25202%2520Homework

Comfort: 4
Completeness: 5

**Comment by amaseda** [comment]
:+1:

Some notes...
• This isn't too important, but rather than using the & symbol outright in your HTML (e.g., `<h3>Founder & CEO</h3>`) you should encode it like so...

``` html
<h3>Founder &amp; CEO</h3>
```

Your webpage will look exactly the same and you don't have to worry about fringe cases where the `&` might throw your browser off.
